#include <iostream>

int main(int argc, char* argv[]) {
    
    try{
    }
    catch(const std::exception& e){
    }
    return 0;
}
